"""empty message

Revision ID: 3212fc98523a
Revises: acb9a5eea993
Create Date: 2023-12-02 15:53:55.448885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3212fc98523a'
down_revision = 'acb9a5eea993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional_info', schema=None) as batch_op:
        batch_op.drop_constraint('professional_info_experience_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional_info', schema=None) as batch_op:
        batch_op.create_unique_constraint('professional_info_experience_key', ['experience'])

    # ### end Alembic commands ###
