"""empty message

Revision ID: 608cf021cfe0
Revises: 
Create Date: 2023-12-14 02:29:34.698788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '608cf021cfe0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('lastname', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=180), nullable=False),
    sa.Column('salt', sa.String(length=180), nullable=False),
    sa.Column('rol', sa.Enum('admin', 'general', name='userrol'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ofertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('address', sa.String(length=80), nullable=False),
    sa.Column('country', sa.String(length=30), nullable=False),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('city', sa.String(length=40), nullable=False),
    sa.Column('category', sa.Enum('mantenimiento', 'limpieza', 'construccion', 'jardineria', 'mudanzas', 'tecnologias', 'negocios', 'salud', 'eventos', 'traducciones', 'idiomas', 'personal_trainning', name='category'), nullable=False),
    sa.Column('service', sa.Enum('remote', 'in_place', name='service_type'), nullable=False),
    sa.Column('images', sa.String(length=250), nullable=True),
    sa.Column('public_image_id', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personal_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=20), nullable=False),
    sa.Column('avatar', sa.String(length=250), nullable=False),
    sa.Column('public_avatar_id', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=30), nullable=False),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('city', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nickname'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('professional_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ocupation', sa.String(length=80), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('skills', sa.String(length=100), nullable=False),
    sa.Column('skills_level', sa.Enum('basic', 'intermediate', 'expert', name='skills_level'), nullable=False),
    sa.Column('certificate', sa.String(length=150), nullable=True),
    sa.Column('institution', sa.String(length=100), nullable=True),
    sa.Column('languages', sa.String(length=20), nullable=False),
    sa.Column('language_level', sa.Enum('basic', 'intermediate', 'expert', 'native', name='language_level'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitudes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('address', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=30), nullable=False),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('city', sa.String(length=40), nullable=False),
    sa.Column('category', sa.Enum('mantenimiento', 'limpieza', 'construccion', 'jardineria', 'mudanzas', 'tecnologias', 'negocios', 'salud', 'eventos', 'traducciones', 'idiomas', 'personal_trainning', name='category'), nullable=False),
    sa.Column('service', sa.Enum('remote', 'in_place', name='service_type'), nullable=False),
    sa.Column('images', sa.String(length=250), nullable=True),
    sa.Column('public_image_id', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=True),
    sa.Column('oferta_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=90), nullable=False),
    sa.ForeignKeyConstraint(['oferta_id'], ['ofertas.id'], ),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('services')
    op.drop_table('solicitudes')
    op.drop_table('professional_info')
    op.drop_table('personal_info')
    op.drop_table('ofertas')
    op.drop_table('user')
    # ### end Alembic commands ###
