"""empty message

Revision ID: acb9a5eea993
Revises: e9e881c2fa64
Create Date: 2023-12-02 02:40:12.218801

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'acb9a5eea993'
down_revision = 'e9e881c2fa64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skills_level', sa.Enum('basic', 'intermediate', 'expert', name='skills_level'), nullable=False))
        batch_op.alter_column('skills',
               existing_type=postgresql.ENUM('basic', 'intermediate', 'expert', name='skills_level'),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional_info', schema=None) as batch_op:
        batch_op.alter_column('skills',
               existing_type=sa.String(length=100),
               type_=postgresql.ENUM('basic', 'intermediate', 'expert', name='skills_level'),
               existing_nullable=False)
        batch_op.drop_column('skills_level')

    # ### end Alembic commands ###
